[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1B5DC9"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F8FC"
textColor = "#0A1B33"
font = "sans serif"

[runner]
magicEnabled = false
fastReruns = true
